name: CI

on: [push]

jobs:
  sas_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . -f jason -o bandit-report.jason


     - name: Upload Artifact
       user: actions/upload-artifact@v3
       if: always()
       with:
         name: bandit-findings
         path: bandit-report.json

    image_scan:
         name: Build Image and Run Image Scan
         runs-on: ubuntu-latest

    steps:
        -name: Checkout code
         uses: actions/checkout@v2

       -name: set up Docker
        uses:  uses: docker-practice/actions-setup-docker@v1
        with: 
           docker_version: '20.10.7'

      -name: Build Docker Image
       run: docker build -f dockerfile -t myapp:latest .

     -name: Docker Scout Scan
      run: 
        curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh
     
     docker scout quickview
     docker scout cves



    
